### ISSUE TITLE
Release a build for Chromium based browser

### ISSUE THREAD

**Issue by Cyberavater** [StuffNoOneCaresAbout/Universal-Bypass#1]
The release is just containing the source code can you add the prebuilt version for Chromium-based browser?

**Comment by FireMasterK** [comment]
[Universal-Bypass.zip](https://github.com/StuffNoOneCaresAbout/Universal-Bypass/files/4821235/Universal-Bypass.zip)
or
https://github.com/StuffNoOneCaresAbout/Universal-Bypass/archive/master.zip

both of them should work fine, the builds Sainan releases are archives of the repo without a few development files.

**Comment by Cyberavater** [comment]
Yes, it's working as expected. thanks!
