### ISSUE TITLE
Remove unneeded massage?

### ISSUE THREAD

**Issue by Cyberavater** [StuffNoOneCaresAbout/Universal-Bypass#2]
"Linkvertise wants to sue Universal Bypass. If you like this extension, help me fight the good fight. Contribute to Universal Bypass.
If you would like to learn more about this, here is some more information."-
Is no longer relevant, no point having it in the UB settings page.

**Comment by FireMasterK** [comment]
Sure, I'll have a look at this tomorrow

**Comment by FireMasterK** [comment]
Fixed in latest commit, you'll have to re-download the extension from here: 
[Universal-Bypass-master.zip](https://github.com/StuffNoOneCaresAbout/Universal-Bypass/files/4831449/Universal-Bypass-master.zip)
