### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by robahearts** [StuffNoOneCaresAbout/Universal-Bypass#3]
So how do I install this one FF instead of Sainan's?

**Comment by bvneet** [comment]
+1

**Comment by Uranite** [comment]
download the repository
extract
delete injection_script and rules.json
go to extension tab
enable developer mode
load unpacked
select the folder
done
profit

**Comment by bvneet** [comment]
No option to load unpacked extension :(

**Comment by robahearts** [comment]
I can only load it as a temporary add-on

**Comment by Uranite** [comment]
oh i didn't read the firefox i will tell u how when im on my pc

**Comment by Uranite** [comment]
i think the only way is to load it as temporary addon but if you close firefox you need to install the extension again
chrome gang
edit: and also  to install the extension select the manifest.json

**Comment by FireMasterK** [comment]
#4
