### ISSUE TITLE
Linkvertise problem related to bypassing waiting time.

### ISSUE THREAD

**Issue by MIHAIdavid22** [StuffNoOneCaresAbout/Universal-Bypass#7]
is it possible to skip the "necessary 85 seconds" in order to get to the link ? it takes 3-20 seconds normally and thats only because of the sometimes article thing heres an example of an link that im reffering to. i dont recommend actually doing anything past the link but its the only valid example that i have of a link that needs to wait 85 seconds in order to bypass.
https://linkvertise.com/48193/krnlc3?o=sharing
ive noticed it automaticly skips the ones that lead to the linkvertise downloader but not shortened urls

**Comment by FireMasterK** [comment]
I'm sorry, what? I don't see any 85 seconds timers.

**Comment by FaolanX** [comment]
It shows for me: https://i.imgur.com/ozEixV2.jpg

**Comment by FireMasterK** [comment]
How much should I change it to?

**Comment by MIHAIdavid22** [comment]
5 seconds
if it doesnt work and it gets detected then 10 seconds

**Comment by FireMasterK** [comment]
Fixed, changed the delay to 10 seconds.
