### ISSUE TITLE
Update the releases or at least delete the old ones?

### ISSUE THREAD

**Issue by FaolanX** [StuffNoOneCaresAbout/Universal-Bypass#8]
The ZIPs in the releases section are outdated and don't work, can you update with the latest one or at least delete them to tidy it up

**Comment by Cyberavater** [comment]
The latest version in Sainan is 13.14.0, here it's 13.12.4

**Comment by FireMasterK** [comment]
Done, follow the build guide from the pinned issues to install.

**Comment by Cyberavater** [comment]
@FireMasterK Can you implement some sort of auto-updater? As it seems the latest from Sainan is 13.15.1 while here it's 13.15.0. I'm just saying that because it'd be also helpful for you to maintain this fork. Thanks for your work!

**Comment by FireMasterK** [comment]
There is an auto-updater, it runs every day at Midnight, GMT.

Currently, it seems like GitHub's actions are having a few problems, they seem to have been stuck on scheduled, it should hopefully be fixed soon.

https://github.com/StuffNoOneCaresAbout/Universal-Bypass/actions
